### ISSUE TITLE
TypeError on npm Start

### ISSUE THREAD

**Issue by sayantan94** [mgechev/js-vnc-demo-project#6]
It needs to be rfb2 
var RFB = require('rfb2');

After making the changes, npm start throws an error: 
`Listening on port 8090
(node:11204) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
Client connected
TypeError: RFB is not a function
    at createRfbConnection (C:\Users\bhowmiks\Experiments\cloneTest\js-vnc-demo-project\server.js:91:9)
    at Socket.<anonymous> (C:\Users\bhowmiks\Experiments\cloneTest\js-vnc-demo-project\server.js:132:15)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at SocketNamespace.handlePacket (C:\Users\bhowmiks\Experiments\cloneTest\js-vnc-demo-project\node_modules\socket.io\lib\namespace.js:335:22)
    at Manager.onClientMessage (C:\Users\bhowmiks\Experiments\cloneTest\js-vnc-demo-project\node_modules\socket.io\lib\manager.js:518:38)
    at WebSocket.Transport.onMessage (C:\Users\bhowmiks\Experiments\cloneTest\js-vnc-demo-project\node_modules\socket.io\lib\transport.js:369:20)
    at Parser.<anonymous> (C:\Users\bhowmiks\Experiments\cloneTest\js-vnc-demo-project\node_modules\socket.io\lib\transports\websocket\hybi-16.js:39:10)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
C:\Users\bhowmiks\Experiments\cloneTest\js-vnc-demo-project\server.js:59
  r.on('error', function (e) {
   ^

TypeError: Cannot read property 'on' of undefined
    at addEventHandlers (C:\Users\bhowmiks\Experiments\cloneTest\js-vnc-demo-project\server.js:59:4)
    at createRfbConnection (C:\Users\bhowmiks\Experiments\cloneTest\js-vnc-demo-project\server.js:103:3)
    at Socket.<anonymous> (C:\Users\bhowmiks\Experiments\cloneTest\js-vnc-demo-project\server.js:132:15)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at SocketNamespace.handlePacket (C:\Users\bhowmiks\Experiments\cloneTest\js-vnc-demo-project\node_modules\socket.io\lib\namespace.js:335:22)
    at Manager.onClientMessage (C:\Users\bhowmiks\Experiments\cloneTest\js-vnc-demo-project\node_modules\socket.io\lib\manager.js:518:38)
    at WebSocket.Transport.onMessage (C:\Users\bhowmiks\Experiments\cloneTest\js-vnc-demo-project\node_modules\socket.io\lib\transport.js:369:20)
    at Parser.<anonymous> (C:\Users\bhowmiks\Experiments\cloneTest\js-vnc-demo-project\node_modules\socket.io\lib\transports\websocket\hybi-16.js:39:10)
    at emitOne (events.js:96:13)`

**Comment by seI3en** [comment]
I forked off before the 'switch to rfb' commit, replaced outdated libs and fixed update polling

it works now on Windows 10 with TightVNC Server 2.8.59 (run as Administrator)

https://github.com/seI3en/js-vnc-demo-project

**Comment by rezamarzban** [comment]
> I forked off before the 'switch to rfb' commit, replaced outdated libs and fixed update polling
> 
> it works now on Windows 10 with TightVNC Server 2.8.59 (run as Administrator)
> 
> https://github.com/seI3en/js-vnc-demo-project

It works but viewing picture color and refresh has some problems ...

**Comment by metinncetinn** [comment]
> I forked off before the 'switch to rfb' commit, replaced outdated libs and fixed update polling
> 
> it works now on Windows 10 with TightVNC Server 2.8.59 (run as Administrator)
> 
> https://github.com/seI3en/js-vnc-demo-project

Thank you. It works for me too. But i had errors :
C:\Users\SCA\Desktop\js-vnc-demo-projectold\server.js:39                                                                for (var i = 0; i < rect.data.length; i += 4) {                                                                                                       ^                                                                                                                                                                                                               TypeError: Cannot read properties of undefined (reading 'length')                                                           at handleFrame (C:\Users\SCA\Desktop\js-vnc-demo-projectold\server.js:39:33)                                          at RfbClient.<anonymous> (C:\Users\SCA\Desktop\js-vnc-demo-projectold\server.js:31:5)                                 at RfbClient.emit (node:events:524:28)                                                                                  at ReadFormatRequest.callback (C:\Users\SCA\Desktop\js-vnc-demo-projectold\node_modules\rfb2\rfbclient.js:478:9)      at ReadFormatRequest.execute (C:\Users\SCA\Desktop\js-vnc-demo-projectold\node_modules\rfb2\unpackstream.js:178:10)                                                                                                                           at UnpackStream.resume (C:\Users\SCA\Desktop\js-vnc-demo-projectold\node_modules\rfb2\unpackstream.js:271:30)         at UnpackStream.write (C:\Users\SCA\Desktop\js-vnc-demo-projectold\node_modules\rfb2\unpackstream.js:199:10)          at Socket.<anonymous> (C:\Users\SCA\Desktop\js-vnc-demo-projectold\node_modules\rfb2\rfbclient.js:23:21)              at Socket.emit (node:events:524:28)                                                                                     at addChunk (node:internal/streams/readable:561:12)                                                                                                                                                                                         Node.js v22.13.1

**Comment by metinncetinn** [comment]
> > I forked off before the 'switch to rfb' commit, replaced outdated libs and fixed update polling
> > it works now on Windows 10 with TightVNC Server 2.8.59 (run as Administrator)
> > https://github.com/seI3en/js-vnc-demo-project
> 
> Thank you. It works for me too. But i had errors : C:\Users\SCA\Desktop\js-vnc-demo-projectold\server.js:39 for (var i = 0; i < rect.data.length; i += 4) { ^ TypeError: Cannot read properties of undefined (reading 'length') at handleFrame (C:\Users\SCA\Desktop\js-vnc-demo-projectold\server.js:39:33) at RfbClient. (C:\Users\SCA\Desktop\js-vnc-demo-projectold\server.js:31:5) at RfbClient.emit (node:events:524:28) at ReadFormatRequest.callback (C:\Users\SCA\Desktop\js-vnc-demo-projectold\node_modules\rfb2\rfbclient.js:478:9) at ReadFormatRequest.execute (C:\Users\SCA\Desktop\js-vnc-demo-projectold\node_modules\rfb2\unpackstream.js:178:10) at UnpackStream.resume (C:\Users\SCA\Desktop\js-vnc-demo-projectold\node_modules\rfb2\unpackstream.js:271:30) at UnpackStream.write (C:\Users\SCA\Desktop\js-vnc-demo-projectold\node_modules\rfb2\unpackstream.js:199:10) at Socket. (C:\Users\SCA\Desktop\js-vnc-demo-projectold\node_modules\rfb2\rfbclient.js:23:21) at Socket.emit (node:events:524:28) at addChunk (node:internal/streams/readable:561:12) Node.js v22.13.1

I completely solved this problem and improved the server for computers with slow internet. I also ensured that the server could remain operational at all times. https://github.com/[metinncetinn/NodeVNCViewer](https://github.com/metinncetinn/NodeVNCViewer)

**Comment by metinncetinn** [comment]
> > I forked off before the 'switch to rfb' commit, replaced outdated libs and fixed update polling
> > it works now on Windows 10 with TightVNC Server 2.8.59 (run as Administrator)
> > https://github.com/seI3en/js-vnc-demo-project
> 
> Thank you. It works for me too. But i had errors : C:\Users\SCA\Desktop\js-vnc-demo-projectold\server.js:39 for (var i = 0; i < rect.data.length; i += 4) { ^ TypeError: Cannot read properties of undefined (reading 'length') at handleFrame (C:\Users\SCA\Desktop\js-vnc-demo-projectold\server.js:39:33) at RfbClient. (C:\Users\SCA\Desktop\js-vnc-demo-projectold\server.js:31:5) at RfbClient.emit (node:events:524:28) at ReadFormatRequest.callback (C:\Users\SCA\Desktop\js-vnc-demo-projectold\node_modules\rfb2\rfbclient.js:478:9) at ReadFormatRequest.execute (C:\Users\SCA\Desktop\js-vnc-demo-projectold\node_modules\rfb2\unpackstream.js:178:10) at UnpackStream.resume (C:\Users\SCA\Desktop\js-vnc-demo-projectold\node_modules\rfb2\unpackstream.js:271:30) at UnpackStream.write (C:\Users\SCA\Desktop\js-vnc-demo-projectold\node_modules\rfb2\unpackstream.js:199:10) at Socket. (C:\Users\SCA\Desktop\js-vnc-demo-projectold\node_modules\rfb2\rfbclient.js:23:21) at Socket.emit (node:events:524:28) at addChunk (node:internal/streams/readable:561:12) Node.js v22.13.1

I completely solved this problem and improved the server for computers with slow internet. I also ensured that the server could remain operational at all times. 
https://github.com/metinncetinn/NodeVNCViewer
